services:
    biberltd.phporient:
        class:        BiberLtd\Bundle\PhpOrientBundle\Services\PhpOrient
        arguments:    ["%orientdb.default.hostname"%, "%orientdb.default.port%", "%orientdb.default.token%"]