services:
    biberltd.phporient:
        class:        BiberLtd\Bundle\PhpOrientBundle\Services\PhpOrient
        arguments:    ["@service_container", "%orientdb.default.hostname%", "%orientdb.default.port%", "%orientdb.default.token%"]